version: '3.8'  # Use version 3.8 of the Compose file format

services:
  backend:
    build:
      context: .  # Dockerfile context
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BASE_PATH=/app
    volumes:
      - .:/app
      - ./Config:/app/Config
      - ./util:/app/util
