definitions:
  Manager.createManagerRequestData:
    properties:
      adminID:
        example: "123456"
        type: string
      name:
        example: longsizhuo
        type: string
      password:
        example: "123456"
        type: string
      phone:
        example: "123456"
        type: string
      repassword:
        example: "123456"
        type: string
    required:
    - adminID
    - name
    type: object
  User.Basic:
    type: object
  User.CodeStructData:
    properties:
      code:
        description: Code 验证码
        type: string
      email:
        type: string
    type: object
  User.CreateUserRequest:
    properties:
      avatar:
        type: string
      dateBirth:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      rePassword:
        type: string
    required:
    - email
    - name
    - password
    - phone
    - rePassword
    type: object
  User.RequestData:
    properties:
      to:
        example: longsizhuo@gmail.com
        format: emailconfigs
        type: string
    required:
    - to
    type: object
  User.loginRequestData:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  User.modifyRequestData:
    properties:
      email:
        example: longsizhuo@gmail.com
        type: string
      password:
        type: string
      repassword:
        type: string
    type: object
info:
  contact: {}
paths:
  /index:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /login:
    post:
      consumes:
      - application/json
      description: 登陆
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/User.loginRequestData'
      produces:
      - application/json
      responses:
        "200":
          description: Login Success
          schema:
            type: string
      summary: 登陆
      tags:
      - User
  /manager/create:
    post:
      consumes:
      - application/json
      description: 创建管理员
      parameters:
      - description: Manager
        in: body
        name: manager
        required: true
        schema:
          $ref: '#/definitions/Manager.createManagerRequestData'
      produces:
      - application/json
      responses:
        "200":
          description: Manager created
          schema:
            type: string
      summary: 创建管理员
      tags:
      - Manager
  /user/create:
    post:
      description: do ping
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/User.CreateUserRequest'
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      summary: 创建用户
      tags:
      - User
  /user/create/sendEmail:
    post:
      consumes:
      - application/json
      description: 发送验证码到指定邮箱，并存储验证码到Redis
      parameters:
      - description: Recipient emailconfigs address
        format: emailconfigs
        in: body
        name: emailconfigs
        required: true
        schema:
          $ref: '#/definitions/User.RequestData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User.RequestData'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Send code
      tags:
      - User
  /user/create/verifyEmail:
    post:
      consumes:
      - application/json
      description: Verify the code/
      parameters:
      - description: email and code
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/User.CodeStructData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User.RequestData'
        "400":
          description: unmarshal error
          schema:
            type: string
      summary: Verify code
      tags:
      - User
  /user/list:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - User
  /user/modifyPasswd:
    post:
      consumes:
      - application/json
      description: 修改密码
      parameters:
      - description: User Email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/User.modifyRequestData'
      produces:
      - application/json
      responses:
        "200":
          description: Password updated
          schema:
            type: string
      summary: 修改密码
      tags:
      - User
  /user/modifyUserInfo:
    post:
      consumes:
      - application/json
      description: 修改用户信息
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/User.Basic'
      produces:
      - application/json
      responses:
        "200":
          description: User information updated
          schema:
            type: string
      summary: 修改用户信息
      tags:
      - User
swagger: "2.0"
