mysql:
  dns: COMP9900:root@tcp(longsizhuo.com:3306)/comp9900?charset=utf8mb4&parseTime=True&loc=Local

#如果连接不上就把longsizhuo.com 改成公网IP：175.178.112.118
redis:
  Addr: "175.178.112.118"
  Password: "COMP9900"
  DB: 0

managers:
  manager: ["longsizhuo","yuboyang","guojiaqi","huayang","wangxuan","wangyunfan"]

